export const pokecolors = {
    bug: "#a4b7a9",
    dark: "#9b9c9b",
    dragon: "#b4d1d5",
    electric: "#f4f4aa",
    fairy: "#d5a3b4",
    fighting: "#d6b3a7",
    fire: "#dda5a7",
    flying: "#b7c2cb",
    ghost: "#adadc4",
    grass: "#a1cab1",
    ground: "#ddc6ab",
    ice: "#cfedfb",
    normal: "#c7babd",
    poison: "#bfabcf",
    psyhic: "#dbaac4",
    rock: "#b6a39d",
    steel: "#bfc8c5",
    water: "#a1baf3"
}